### ISSUE TITLE
can only return to last edit after editing current location

### ISSUE THREAD

**Issue by zuthan** [Stuk/sublime-edit-history#8] opened 2012-08-30 01:31 UTC
It seems that I can only use the command previous_edit from near a location that I have just edited. This command should work from anywhere, though.

**Comment by Stuk** [comment] 2012-08-31 21:08
Can you give some steps to reproduce? It seems to be working fine for me.

**Comment by zuthan** [comment] 2012-09-01 00:28
I created a new file into which I pasted 5 paragraphs of lorem ipsum text.
I made an edit at the end and then pressed ctrl+home to go to the start of
the document. When I ran the previous_edit command, nothing happened. I
then typed some more text (at the start of the document this time). When I
ran previous_edit again, it jumped to my first edit at the bottom of the
document.

I think what you need is to add to the start of PreviousEditCommand a
clause which checks if the current selection is more than the threshold
away from the current edit position and, if so, to move the selection back
to the current edit position without any changes to the history.

**Comment by zuthan** [comment] 2012-09-01 03:17
See #9

**Comment by Stuk** [comment] 2012-09-05 04:09
I see. I've merged your pull so this is sorted. Thanks very much!

**Closed as completed** 2013-04-07 19:34 UTC
